# GitHub Pages 配置文件
# 告诉 GitHub Pages 这是一个静态网站，不需要 Jekyll 处理

# 包含所有文件，包括以 _ 开头的文件夹
include:
  - "_*"
  - ".*"

# 排除不需要的文件
exclude:
  - "README.md"
  - "LICENSE"
  - ".git"
  - ".github"
  - "node_modules"
  - "*.log"

# 设置默认页面
defaults:
  - scope:
      path: ""
    values:
      layout: default

# 启用相对链接
relative_links:
  enabled: true
  collections: false

# 插件（GitHub Pages 默认支持）
plugins:
  - jekyll-relative-links